// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;






class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkLisWryk_xzI6YvvB8jyT_D-Hsjm3IBg',
    appId: '1:840457112099:web:f15f5323f52d0e5a107f96',
    messagingSenderId: '840457112099',
    projectId: 'hourtracker-13ecb',
    authDomain: 'hourtracker-13ecb.firebaseapp.com',
    storageBucket: 'hourtracker-13ecb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQWvFatfIA-sQru_jZpl1wcrJhxhGebnA',
    appId: '1:840457112099:android:976930656bdb9786107f96',
    messagingSenderId: '840457112099',
    projectId: 'hourtracker-13ecb',
    storageBucket: 'hourtracker-13ecb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCef-URMKZwnkcG2zwJ4QK-sRkoyobmyVk',
    appId: '1:840457112099:ios:9865ddd2144e6ae6107f96',
    messagingSenderId: '840457112099',
    projectId: 'hourtracker-13ecb',
    storageBucket: 'hourtracker-13ecb.appspot.com',
    iosBundleId: 'com.example.hourLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCef-URMKZwnkcG2zwJ4QK-sRkoyobmyVk',
    appId: '1:840457112099:ios:6cf84f23e4a476f8107f96',
    messagingSenderId: '840457112099',
    projectId: 'hourtracker-13ecb',
    storageBucket: 'hourtracker-13ecb.appspot.com',
    iosBundleId: 'com.example.hourLog.RunnerTests',
  );
}
